#%RAML 1.0
title: API Hypervision
version: 1.0
baseUri: https://hypervision.laravel5.intranatixis.com/api
baseUriParameters: {}
protocols:
- HTTPS
- HTTP
documentation:
- title: API Hypervision
  content: "Le portail Hypervision permet d'enrichir les événements qui remontent dans l'hyperviseur BEM (BMC \r\nEvent Manager) depuis les outils suivants : \r\nControlM V8, Hobbit, Newtest,Sentinel, Zabbix"
securitySchemes:
  auth:
    type: Basic Authentication
types:
  GetallastreinteRequest:
    example:
      value:
        params:
          astreinte_id: 75
        select:
          astreinte_group: ''
    displayName: GetallastreinteRequest
    type: object
    properties:
      params:
        required: true
        displayName: params
        type: Params
      select:
        required: true
        displayName: select
        type: Select
  Params:
    example:
      value:
        astreinte_id: 75
    displayName: Params
    type: object
    properties:
      astreinte_id:
        required: true
        displayName: astreinte_id
        type: integer
        format: int32
  Select:
    example:
      value:
        astreinte_group: ''
    displayName: Select
    type: object
    properties:
      astreinte_group:
        required: true
        displayName: astreinte_group
        type: string
  GetControlmjobRequest:
    example:
      value:
        param:
          data_center: pifa1
    displayName: GetControlmjobRequest
    type: object
    properties:
      param:
        required: true
        displayName: param
        type: Param
  Param:
    example:
      value:
        data_center: pifa1
    displayName: Param
    type: object
    properties:
      data_center:
        required: true
        displayName: data_center
        type: string
/astreinte:
  post:
    displayName: Getallastreinte
    body:
      application/json:
        example:
          value:
            params:
              astreinte_id: 75
            select:
              astreinte_group: ''
        displayName: Body
        type: GetallastreinteRequest
    securedBy:
    - auth
    headers:
      Content-Type:
        required: true
        example:
          value: application/json
        displayName: Content-Type
        type: string
    responses:
      200:
        description: Success
/newtest:
  get:
    displayName: DDA
    description: Export des enrichissements par outils pour intregration dans la BEM
    securedBy:
    - auth
    responses:
      200:
        description: Success
/controlm/get_job:
  post:
    displayName: GetControlmjob
    body:
      application/json:
        example:
          value:
            param:
              data_center: pifa1
        displayName: Body
        type: GetControlmjobRequest
    securedBy:
    - auth
    headers:
      Content-Type:
        required: true
        example:
          value: application/json
        displayName: Content-Type
        type: string
    responses:
      200:
        description: Success
/department/get_deparment:
  get:
    displayName: Getalldepartments
    securedBy:
    - auth
    responses:
      200:
        description: Success
  /110:
    get:
      displayName: Getonedepartment
      securedBy:
      - auth
      responses:
        200:
          description: Success
/zabbix/hostgroup:
  get:
    displayName: GetallZabbixHostgroups
    securedBy:
    - auth
    responses:
      200:
        description: Success
  post:
    displayName: CreateZabbixHostgroup
    body:
      multipart/form-data:
        type: object
        properties:
          id_department:
            required: true
            example:
              value: 110
            displayName: id_department
            type: integer
            format: int32
          hostgroup:
            required: true
            example:
              value: toto
            displayName: hostgroup
            type: string
    securedBy:
    - auth
    headers:
      Content-Type:
        required: true
        example:
          value: application/x-www-form-urlencoded
        displayName: Content-Type
        type: string
    responses:
      200:
        description: Success
  /256:
    get:
      displayName: GetoneZabbixHostgroup
      securedBy:
      - auth
      responses:
        200:
          description: Success
